config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events

  get 'tags/:tag', to: 'events#index', as: :tag

  root 'events#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :organizers, class_name: "User"

	acts_as_taggable

	extend FriendlyId
  	friendly_id :slug_candidates, use: :slugged

  	def slug_candidates
  		[:title,[:title, :location]]
  	end

	def event_owner(organizer_id)
		User.find_by id: organizer_id
	end	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :organized_events, class_name: "Event", foreign_key: "organizer_id"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:new, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    if params[:tag]
      @events = Event.tagged_with(params[:tag])
    else
      @events = Event.all
    end  
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event_owner = @event.event_owner(@event.organizer_id)
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.organized_events.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def event_owner!
      authenticate_user!
      if @event.organizer_id != current_user.id
        redirect_to events_path
        flash[:notice] = "You do not have enough permission to do this"
      end  
    end

    def set_event
      @event = Event.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :start_date, :end_date, :location, :agenda, :address, :organizer_id, :posted, :updated, :tag_list)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.haml
= form_for(@event) do |f|
  - if @event.errors.any?
    #error_explanation
      %h2
        = pluralize(@event.errors.count, "error")
        prohibited this event from being saved:
      %ul
        - @event.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :title
    %br/
    = f.text_field :title
  .field
    = f.label :start_date
    %br/
    = f.text_field :start_date
  .field
    = f.label :end_date
    %br/
    = f.text_field :end_date
  .field
    = f.label :location
    %br/
    = f.text_field :location
  .field
    = f.label :agenda
    %br/
    = f.text_area :agenda
  .field
    = f.label :address
    %br/
    = f.text_area :address
  .field
    = f.label :tag_list, "Tags (seperated by commas)"
    %br/
    = f.text_field :tag_list
  .actions
    = f.submit

app/views/events/edit.html.haml
%h1 Editing event
= render 'form'
= link_to 'Show', @event
|
\#{link_to 'Back', events_path}

app/views/events/index.html.haml
%h1 Listing events
%table
  %thead
    %tr
      %th Title
      %th Start date
      %th End date
      %th Location
      %th Agenda
      %th Address
      %th Organizer
      %th Tags
      %th Posted
      %th Updated
      %th{:colspan => "3"}
  %tbody
    - @events.each do |event|
      %tr
        %td= event.title
        %td= event.start_date.strftime("%d %B %Y")
        %td= event.end_date.strftime("%d %B %Y")
        %td= event.location
        %td= event.agenda
        %td= event.address
        - @event_owner = event.event_owner(event.organizer_id)  #remember this
        %td= @event_owner.email
        %td= raw event.tag_list.map {|t| link_to t, tag_path(t)}.join(', ')
        %td= event.posted
        %td= event.updated
        %td= link_to 'Show', event
        %td= link_to 'Edit', edit_event_path(event)
        %td= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Event', new_event_path

app/views/events/new.html.haml
.row
  .small-12.medium-8.large-6.columns
    %h1 New event
    = render 'form'
    = link_to 'Back', events_path

app/views/events/show.html.haml
%p#notice= notice
%p
  %strong Title:
  = @event.title
%p
  %strong Start date:
  = @event.start_date.strftime("%d %B %Y")
%p
  %strong End date:
  = @event.end_date.strftime("%d %B %Y")
%p
  %strong Location:
  = @event.location
%p
  %strong Agenda:
  = @event.agenda
%p
  %strong Address:
  = @event.address
%p
  %strong Organizer:
  = @event_owner.email
%p
  %strong Tags:
  =raw @event.tag_list.map {|t| link_to t, tag_path(t)}.join(', ')

= link_to 'Edit', edit_event_path(@event)
|
\#{link_to 'Back', events_path}

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Evento"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tags
  %body
    .top-bar
      .top-bar-section
        .title-area
          .name
            %ul
              %li 
                %h1=link_to Evento, root_path
        .left
          %ul
            %li=link_to "Event", events_path        
        .right
          %ul
            - if user_signed_in?
              %li=link_to "#{current_user.email}"
              %li=link_to "Logout", destroy_user_session_path, method: :delete
            - else
              %li=link_to "Login", new_user_session_path
              %li=link_to "Signup", new_user_registration_path  
    
    = yield

    %h2 Tags:
    - tag_cloud Event.tag_counts, %w[s m l] do |tag, css_class|
      = link_to tag.name, tag_path(tag.name), class: css_class

    = javascript_include_tag "application"

app/views/users/shared/_links.haml
- if controller_name != 'sessions'
  = link_to "Sign in", new_session_path(resource_name), class: :button
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name), class: :button
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider)
    %br/